# Generated by Django 3.1.2 on 2021-02-09 05:41

import abstract.fields.status
import abstract.fields.unix_timestamp
from django.db import migrations, models
import django.db.models.deletion
import item.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', abstract.fields.status.StatusField(choices=[('R', 'Remove'), ('W', 'Waiting'), ('A', 'Active')], default='W', max_length=1)),
                ('created_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now_add=True)),
                ('updated_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', abstract.fields.status.StatusField(choices=[('R', 'Remove'), ('W', 'Waiting'), ('A', 'Active')], default='W', max_length=1)),
                ('created_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now_add=True)),
                ('updated_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now=True)),
                ('name', models.CharField(default='Name of book', max_length=100, unique=True)),
                ('price', models.IntegerField(default=0, validators=[item.models.validate_positive_number])),
                ('first_price', models.IntegerField(default=0, validators=[item.models.validate_positive_number])),
                ('short_description', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
                ('number_pages', models.IntegerField(default=0, validators=[item.models.validate_positive_number])),
                ('issuing_company', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('rating_count', models.IntegerField(default=0, validators=[item.models.validate_positive_number])),
                ('rating_sum', models.IntegerField(default=0, validators=[item.models.validate_positive_number])),
                ('authors', models.ManyToManyField(related_name='Authors_of_book', to='item.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', abstract.fields.status.StatusField(choices=[('R', 'Remove'), ('W', 'Waiting'), ('A', 'Active')], default='W', max_length=1)),
                ('created_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now_add=True)),
                ('updated_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now=True)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(default='description of image', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', abstract.fields.status.StatusField(choices=[('R', 'Remove'), ('W', 'Waiting'), ('A', 'Active')], default='W', max_length=1)),
                ('created_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now_add=True)),
                ('updated_at', abstract.fields.unix_timestamp.UnixTimeStamp(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='Categories_of_book', to='item.Category'),
        ),
    ]
