# Generated by Django 3.1.2 on 2021-04-02 10:29

from django.db import migrations, models
import django.db.models.deletion
import product.models
import utils.fields.status
import utils.fields.timestamp
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('name', models.CharField(default='Name of book', max_length=100)),
                ('price', models.IntegerField(default=0, validators=[product.models.validate_positive_number])),
                ('first_price', models.IntegerField(default=0, validators=[product.models.validate_positive_number])),
                ('short_description', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
                ('number_pages', models.IntegerField(default=0, validators=[product.models.validate_positive_number])),
                ('issuing_company', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('rating_count', models.IntegerField(default=0, validators=[product.models.validate_positive_number])),
                ('rating_sum', models.IntegerField(default=0, validators=[product.models.validate_positive_number])),
                ('sku', models.IntegerField(default=-1)),
                ('authors', models.ManyToManyField(related_name='Authors_of_book', to='product.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(default='description of image', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('fake_id', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='Categories_of_book', to='product.Category'),
        ),
    ]
