# Generated by Django 3.1.2 on 2021-03-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='Name of book', max_length=100),
        ),
    ]
