# Generated by Django 3.1.2 on 2021-03-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sku',
            field=models.IntegerField(default=-1),
        ),
    ]
