# Generated by Django 3.1.2 on 2021-04-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fake_id',
        ),
    ]
