const FieldType = Object.freeze({
    TEXT: 'TEXT',
    TEXTAREA: 'TEXTAREA',
    NUMBER: 'NUMBER',
    SINGLE_SELECT: 'SINGLE_SELECT',
    MULTIPLE_SELECT: 'MULTIPLE_SELECT',
    MULTIPLE_SELECT_MODE_TAGS: 'MULTIPLE_SELECT_MODE_TAGS',
    RADIO: 'RADIO',
    DATE: 'DATE',
    TIME: 'TIME',
    CHECKBOX: 'CHECKBOX',
    TEXT_EDITOR: 'TEXT_EDITOR',
    TEXT_WITH_BTN: 'TEXT_WITH_BTN',
    PASSWORD: 'PASSWORD',
})

export default FieldType;