const ToastType = Object.freeze({
    TOAST_TYPE_DEFAULT: 'TOAST_TYPE_DEFAULT',
    TOAST_TYPE_ERROR: 'TOAST_TYPE_ERROR',
    TOAST_TYPE_SUCCESS: 'TOAST_TYPE_SUCCESS',
    TOAST_TYPE_WARNING: 'TOAST_TYPE_WARNING',
    TOAST_TYPE_INFO: 'TOAST_TYPE_INFO',
})

export default ToastType;