# Generated by Django 3.1.3 on 2021-07-20 14:53

from django.db import migrations, models
import utils.fields.status
import utils.fields.timestamp
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email_address')),
                ('is_admin', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
