# Generated by Django 3.1.2 on 2021-04-02 10:29

from django.db import migrations, models
import django.db.models.deletion
import utils.fields.status
import utils.fields.timestamp
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', utils.fields.status.StatusField(choices=[('A', 'Active'), ('W', 'Watting'), ('R', 'Remove')], default='W', max_length=1)),
                ('created_at', utils.fields.timestamp.TimeStamp(auto_now_add=True)),
                ('updated_at', utils.fields.timestamp.TimeStamp(auto_now=True)),
                ('rating', models.IntegerField()),
                ('timestampe', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('header', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
