# Generated by Django 3.1.2 on 2021-04-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_interaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='timestampe',
        ),
    ]
